name: ci

on:
  pull_request:
    branches: [ master ]

jobs:

  stack-matrix-strategy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-strategy.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - id: matrix-strategy
      uses: ./.github/actions/matrix-strategy-paths
      with:
        matrix-strategy: |
          admin:
          - 'stacks/admin/**'
          app:
          - 'stacks/app/**'
          demo:
          - 'stacks/demo/**'
          fulfilment:
          - 'stacks/fulfilment/**'
          packer:
            - 'stacks/packer/**'
          platform:
          - 'stacks/platform/**'
          satellite:
          - 'stacks/satellite/**'
          scans:
            - 'stacks/scans/**'
          simulator:
          - 'stacks/simulator/**'
        changed-files: git --no-pager diff --name-only HEAD origin/master

  stack:
    needs: stack-matrix-strategy
    if: ${{ needs.stack-matrix-strategy.outputs.matrix != '[]' }}
    strategy:
      matrix:
        stack: ${{ fromJson(needs.stack-matrix-strategy.outputs.matrix) }}
    uses: ./.github/workflows/ci-stack.yml
    with:
      stack: ${{ matrix.stack }}
